[package]
name = "wallet"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "wallet"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = { version = "0.35.0", features = ["nif_version_2_16"] }
ethers = "1.0.2"
anyhow = "1.0"